#!/bin/sh
VERSION=`cat VERSION`
TGZ_DEST="$HOME/shiro.dreamhost.com/scheme/vault/"
RPMDIR="$HOME/rpm"

while [ $# -gt 0 ]; do
  case $1 in
    gen) gen=yes; shift ;;
    tgz) gen=yes; tgz=yes; shift ;;
    *) echo "DIST [gen|tgz]"; exit 0;;
  esac
done

if [ "$gen" = "yes" ]; then
  rm -f acinclude.m4
  cp `gauche-config --ac`/aclocal.m4 acinclude.m4
  aclocal
  automake -a -c
  autoconf
  ./configure
fi

if [ "$tgz" = "yes" ]; then
  make dist
fi

