#!/bin/sh
TGZ_DEST="$HOME/shiro.dreamhost.com/scheme/vault/"
RPMDIR="$HOME/rpm"

while [ $# -gt 0 ]; do
  case $1 in
    gen) gen=yes; shift ;;
    tgz) gen=yes; tgz=yes; shift ;;
    *) echo "DIST [gen|tgz]"; exit 0;;
  esac
done

if [ "$gen" = "yes" ]; then
  autoconf -I `gauche-config --ac`
  ./configure
fi

if [ "$tgz" = "yes" ]; then
  make distclean
  ./configure
  if [ ! -f VERSION ]; then echo "no VERSION -- something wrong?"; exit 1; fi
  VERSION=`cat VERSION`
  rm -rf ../WiLiKi-$VERSION
  rm -f DIST_ECLUDE_X
  cat DIST_EXCLUDE > DIST_EXCLUDE_X
  find . -name CVS -print -prune >> DIST_EXCLUDE_X

  mkdir ../WiLiKi-$VERSION
  tar cvfX - DIST_EXCLUDE_X . | (cd ../WiLiKi-$VERSION; tar xf -)
  (cd ..; tar cvf - WiLiKi-$VERSION | gzip -9 > WiLiKi-$VERSION.tgz)
  rm -rf ../WiLiKi-$VERSION
fi

